@baseURL = http://localhost:3003/api/blogs
@blogId = 5ffaf2962884257e9ac38f09
@jwt = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InFxeCIsImlkIjoiNWZlZDNjOTljNzFmODcxMDk4YTcwMTViIiwiaWF0IjoxNjA5Mzg0ODUxfQ.sxzalrATWDdFk0q_gSFP2AzREjY8U3t9zjI_dSAQUCs
GET {{baseURL}}

###
DELETE {{baseURL}}/{{blogId}}
Authorization: {{jwt}}

###
PUT {{baseURL}}/{{blogId}}
Content-Type: application/json

{
  "title": "一图看懂小米11手机：骁龙888旗舰3999元起",
  "author": "骑士",
  "url": "https://www.ithome.com/0/527/235.htm",
  "likes": 120
}

###
POST {{baseURL}}
Content-Type: application/json
Authorization: {{jwt}}

{
  "title": "一图看懂小米11手机：骁龙888旗舰3999元起",
  "author": "骑士",
  "url": "https://www.ithome.com/0/527/235.htm",
  "likes": 109
}

###
POST {{baseURL}}/{{blogId}}/comments
Content-Type: application/json

{
  "comment": "test"
}