@baseURL = http://localhost:3003/api/users
@userid = 5ff5dcca8f967202b4d9d3a4

###
GET {{baseURL}}

###
GET {{baseURL}}/{{userid}}

###
POST {{baseURL}}
Content-Type: application/json

{
  "username": "qqx",
  "name": "qiuxu",
  "password": "qqxqqx123"
}